CREATE DATABASE WSTower;

USE WSTower;

CREATE TABLE TipoUsuario(
idTipoUsuario INT PRIMARY KEY IDENTITY,
Titulo VARCHAR(30)UNIQUE NOT NULL
);

CREATE TABLE  Usuario(
idUsuario INT PRIMARY KEY IDENTITY,
NomeUsuario VARCHAR(50)NOT NULL,
Email VARCHAR(60)UNIQUE NOT NULL,
senha VARCHAR(30)NOT NULL,
idTipoUsuario INT FOREIGN KEY REFERENCES TipoUsuario(idTipoUsuario)NOT NULL
);

CREATE TABLE Estadio(
idEstadio INT PRIMARY KEY IDENTITY,
NomeEstadio VARCHAR(50)UNIQUE NOT NULL
);

CREATE TABLE TipoEvento(
idTipoEvento INT PRIMARY KEY IDENTITY,
Titulo VARCHAR(100)UNIQUE NOT NULL
);


CREATE TABLE Evento(
idEvento INT PRIMARY KEY IDENTITY,
NomeEvento VARCHAR(100)NOT NULL,
DataEvento DATE NOT NULL,
Descricao Text NOT NULL,
idEstadio INT FOREIGN KEY REFERENCES Estadio(idEstadio)NOT NULL,
idTipoEvento INT FOREIGN KEY REFERENCES TipoEvento(idTipoEvento)NOT NULL,
AcessoLivre BIT NOT NULL
);